var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "basic_oscillators.h", "basic__oscillators_8h.html", "basic__oscillators_8h" ],
    [ "bow_table.h", "bow__table_8h_source.html", null ],
    [ "bowed_string.h", "bowed__string_8h_source.html", null ],
    [ "chorus.h", "chorus_8h_source.html", null ],
    [ "circular_buffer.h", "circular__buffer_8h_source.html", null ],
    [ "delayline.h", "delayline_8h_source.html", null ],
    [ "dsp_utils.h", "dsp__utils_8h_source.html", null ],
    [ "filter.h", "filter_8h_source.html", null ],
    [ "interpolation_strategy.h", "interpolation__strategy_8h_source.html", null ],
    [ "junction.h", "junction_8h_source.html", null ],
    [ "line.h", "line_8h_source.html", null ],
    [ "phaseshapers.h", "phaseshapers_8h_source.html", null ],
    [ "rms.h", "rms_8h_source.html", null ],
    [ "sin_table.h", "sin__table_8h_source.html", null ],
    [ "sinc_resampler.h", "sinc__resampler_8h_source.html", null ],
    [ "sinc_table.h", "sinc__table_8h_source.html", null ],
    [ "smooth_param.h", "smooth__param_8h_source.html", null ],
    [ "string_ensemble.h", "string__ensemble_8h_source.html", null ],
    [ "termination.h", "termination_8h_source.html", null ],
    [ "waveguide.h", "waveguide_8h_source.html", null ],
    [ "waveguide_gate.h", "waveguide__gate_8h_source.html", null ],
    [ "window_functions.h", "window__functions_8h_source.html", null ]
];